name: ci

  workflow_dispatch:
    inputs:
      tag:
        description: 'The docker image tag to be used'
        required: false
        default: 'latest'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      USERNAME: dgotlieb # change me to your docker hub username!
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: $USERNAME/${GITHUB_REPOSITORY#*/}:latest
